general:
  debug: false
  do_train: true
  do_eval: false
  get_mismatched: true
  evaluate_during_training: true
  output_dir: outputs
  save_steps: 500
  validation_every_n_epoch: 1

train:
  accumulation_steps: 1
  adam_eps: 1e-8
  auto_lr: false
  alpha: 0.5
  discriminative_learning: true
  dropout: 0.2
  layer_lr_decay: 0.95
  learning_rates: [5e-5]
  logging_steps: 50
  lr_scheduler: false
  max_grad_norm: 1.0
  num_epochs: 10
  warmup_ratio: 0.06
  warmup_steps: true
  weight_decay: 0.01
  optimizer: adamw

model:
  _target_: bert_squeeze.distillation.seq2seq_distiller.Seq2SeqDistiller
  teacher:
    _target_: bert_squeeze.models.lt_t5.SimpleT5Model
    task: "summarization"
    pretrained_model: "t5-small"
    training_config: ${train}
    generate_kwargs:
      do_sample: false
  student:
    _target_: bert_squeeze.models.lt_t5.SimpleT5Model
    task: "summarization"
    pretrained_model: "t5-small"
    training_config: ${train}
    generate_kwargs:
      do_sample: false
  training_config: ${train}

data:
  _target_: bert_squeeze.data.modules.distillation_module.DistillationDataModule
  teacher_module:
    _target_: bert_squeeze.data.modules.transformer_module.Seq2SeqTransformerDataModule
    dataset_config:
      is_local: false
      target_col:
      path:
      split:
      source_col:
    max_target_length: 32
    max_source_length: 256
    tokenizer_name: ${model.teacher.pretrained_model}
  student_module:
    _target_: bert_squeeze.data.modules.transformer_module.Seq2SeqTransformerDataModule
    dataset_config:
      is_local: ${data.teacher_module.dataset_config.is_local}
      path: ${data.teacher_module.dataset_config.path}
      split: ${data.teacher_module.dataset_config.split}
      source_col: ${data.teacher_module.dataset_config.source_col}
      target_col: ${data.teacher_module.dataset_config.target_col}
    tokenizer_name: ${model.student.pretrained_model}
    max_target_length: ${data.teacher_module.max_target_length}
    max_source_length: ${data.teacher_module.max_source_length}

callbacks:
