task:
  name: train

general:
  do_train: true
  do_eval: false
  debug: false
  labels:
    - sadness
    - joy
    - love
    - anger
    - fear
    - surprise
  output_dir: outputs
  save_steps: 500
  validation_every_n_epoch: 1
  evaluate_during_training: true
  get_mismated: true

train:
  training_batch_size: 16
  eval_batch_size: 16
  num_epochs: 10
  dropout: 0.2
  objective: ce
  smoothing: 0.1
  optimizer: sgd
  learning_rates: [ 2e-3 ]
  auto_lr: false
  lr_scheduler: true
  max_grad_norm: 1.0
  accumulation_steps: 1
  logging_steps: 100

model:
  _target_: bert-squeeze.models.lstm.LtLSTM
  training_config: ${train}
  vocab_len: 20000
  hidden_dim: 128
  num_labels: 6
  name: lstm

data:
  _target_: bert-squeeze.data.modules.lstm_module.LSTMDataModule
  dataset_config:
    is_local: false
    name: emotion
    split:
    text_col: text
    label_col: label
  max_features: ${model.vocab_len}
  train_batch_size: ${train.training_batch_size}
  eval_batch_size: ${train.eval_batch_size}

neptune:
  user_name: julesbelveze
  project: bert-tricks
  tags: [ ]
  logger:
    _target_: neptune.new.integrations.pytorch_lightning.NeptuneLogger
    project: ${neptune.user_name}/${neptune.project}
    name: ${task.name}

