# @package model
_target_: bert_squeeze.models.lt_bert.LtSequenceClassificationCustomBert
num_labels: 2
pretrained_model: bert-base-cased
training_config: ${train}
scorer:
  _target_: bert_squeeze.utils.scorers.sequence_classification_scorer.BaseSequenceClassificationScorer
  labels: ${task.labels}

