task:
  name: train

general:
  do_train: true
  do_eval: false
  debug: false
  labels:
    - sadness
    - joy
    - love
    - anger
    - fear
    - surprise
  output_dir: outputs
  save_steps: 500
  validation_every_n_epoch: 1
  evaluate_during_training: true
  get_mismatched: true

train:
  training_batch_size: 16
  eval_batch_size: 16
  num_epochs: 10
  dropout: 0.2
  objective: ce
  smoothing: 0.1
  optimizer: sgd
  weight_decay: 0.01
  discriminative_learning: false
  learning_rates: [ 2e-1 ]
  auto_lr: false
  layer_lr_decay: 0.95
  lr_scheduler: true
  adam_eps: 1e-8
  warmup_ratio: 0.06
  warmup_steps: true
  max_grad_norm: 1.0
  accumulation_steps: 1
  logging_steps: 100

model:
  _target_: bert-squeeze.models.lr.BowLogisticRegression
  training_config: ${train}
  vocab_size: 5000
  embed_dim: 256
  num_labels: 6
  name: bow_lr

data:
  _target_: bert-squeeze.data.modules.lr_module.LrDataModule
  dataset_config:
    is_local: false
    path: emotion
    split:
    text_col: text
    label_col: label
  max_features: ${model.vocab_size}
  train_batch_size: ${train.training_batch_size}
  eval_batch_size: ${train.eval_batch_size}

neptune:
  user_name: julesbelveze
  project: bert-tricks
  tags: [ ]
  logger:
    _target_: neptune.new.integrations.pytorch_lightning.NeptuneLogger
    project: ${neptune.user_name}/${neptune.project}
    name: ${task.name}

