name: Documentation
on:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-copybutton sphinxext-opengraph myst-parser autodoc-pydantic nbsphinx
          sudo apt-get install -y pandoc
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: "./docs"
          install_requirements: "true"
      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
