name: CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: poetry env use 3.9

      - name: Install dev dependencies
        run: poetry install --only dev --no-root

      - name: Check formatting
        run: poetry run task check-formatting

      - name: Run lint
        run: poetry run task lint

      - name: Run type checking
        run: poetry run mypy bert_squeeze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: poetry env use 3.9

      - name: Install dependencies
        run: poetry install --with dev --no-root

      - name: Run tests
        run: poetry run task test
