name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Build and PyPI Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.9"
          cache: true

      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish --token $PYPI_TOKEN
