name: Publish to PyPI
on:
  release:
    types: [published]

env:
  POETRY_VERSION: 1.3.0

jobs:
  pypi_release:
    name: Poetry Build and PyPI Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install --upgrade pip
          pip install lockfile poetry==$POETRY_VERSION
          poetry install
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Build package
        run: poetry install
      - name: Publish package
        run: poetry publish --build