name: Publish to PyPI
on:
  release:
    types: [published]

env:
  POETRY_VERSION: 1.3.0

jobs:
  pypi_release:
    name: Poetry Build and PyPI Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==$POETRY_VERSION
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Build package
        run: poetry install
      - name: Publish package
        run: poetry publish --build